#!/bin/bash

# Create a VM Instance
gcloud compute instances create my-vm \
    --machine-type=e2-medium \
    --image-family=debian-11 \
    --image-project=debian-cloud \
    --zone=us-central1-a \
    --tags=http-server,https-server

# Create an Instance Template
gcloud compute instance-templates create my-template \
    --machine-type=e2-medium \
    --image-family=debian-11 \
    --image-project=debian-cloud \
    --tags=http-server,https-server

# Create a Managed Instance Group
gcloud compute instance-groups managed create my-group \
    --base-instance-name=my-vm \
    --size=1 \
    --template=my-template \
    --zone=us-central1-a

# Configure Auto-Scaling
gcloud compute instance-groups managed set-autoscaling my-group \
    --max-num-replicas=5 \
    --min-num-replicas=1 \
    --target-cpu-utilization=0.7 \
    --cool-down-period=60 \
    --zone=us-central1-a

# Set Up Firewall Rules
gcloud compute firewall-rules create allow-http \
    --allow=tcp:80 \
    --target-tags=http-server

gcloud compute firewall-rules create allow-https \
    --allow=tcp:443 \
    --target-tags=https-server
